const rudimentList = () => {
    return [
        {id: 'rudi1',
        name: 'Single Stroke Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/1.png',
        link: 'https://vicfirth.zildjian.com/education/01-single-stroke-roll.html'},
        {id: 'rudi2',
        name: 'Single Stroke Four',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/2.png',
        link: 'https://vicfirth.zildjian.com/education/02-single-stroke-four.html'},
        {id: 'rudi3',
        name: 'Single Stroke Seven',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/3.png',
        link: 'https://vicfirth.zildjian.com/education/03-single-stroke-seven.html'},
        {id: 'rudi4',
        name: 'Multiple Bounce Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/4.png',
        link: 'https://vicfirth.zildjian.com/education/04-mutliple-bounce-roll.html'},
        {id: 'rudi5',
        name: 'Triple Stroke Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/5.png',
        link: 'https://vicfirth.zildjian.com/education/05-triple-stroke-roll.html'},
        {id: 'rudi6',
        name: 'Double Stroke (Open) Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/6.png',
        link: 'https://vicfirth.zildjian.com/education/06-double-stroke-roll.html'},
        {id: 'rudi7',
        name: 'Five Stroke Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/7_1.png',
        link: 'https://vicfirth.zildjian.com/education/07-five-stroke-roll.html'},
        {id: 'rudi8',
        name: 'Six Stroke Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/8.png',
        link: 'https://vicfirth.zildjian.com/education/08-six-stroke-roll.html'},
        {id: 'rudi9',
        name: 'Seven Stroke Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/9_1.png',
        link: 'https://vicfirth.zildjian.com/education/09-seven-stroke-roll.html'},
        {id: 'rudi10',
        name: 'Nine Stroke Roll',
        img: 'https://vicfirth.zildjian.com/media/amasty/blog/10.png',
        link: 'https://vicfirth.zildjian.com/education/10-nine-stroke-roll.html'}
    ]
}

export default rudimentList